from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial=True
    dependencies=[]
    operations=[
        migrations.CreateModel(name='Event',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=200)),('event_type',models.CharField(max_length=100)),('date',models.DateField()),('budget',models.DecimalField(decimal_places=2,default=0,max_digits=12)),('expected_participants',models.PositiveIntegerField(default=0)),('status',models.CharField(choices=[('Created','Created'),('Execution','Execution'),('Completed','Completed')],default='Created',max_length=20))]),
        migrations.CreateModel(name='Venue',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=150)),('location',models.CharField(max_length=200)),('capacity',models.PositiveIntegerField()),('available',models.BooleanField(default=True))]),
        migrations.AddField(model_name='event',name='venue',field=models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='events',to='core.venue')),
        migrations.CreateModel(name='Resource',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=150)),('total_quantity',models.PositiveIntegerField(default=0)),('available_quantity',models.PositiveIntegerField(default=0))]),
        migrations.CreateModel(name='Attendee',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('registration_id',models.CharField(max_length=30,unique=True)),('name',models.CharField(max_length=120)),('email',models.EmailField(max_length=254)),('phone',models.CharField(max_length=10)),('college',models.CharField(max_length=150)),('department',models.CharField(blank=True,max_length=100)),('attendance_status',models.CharField(choices=[('Registered','Registered'),('Checked In','Checked In'),('Absent','Absent'),('Cancelled','Cancelled')],default='Registered',max_length=20)),('event',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='attendees',to='core.event'))]),
        migrations.CreateModel(name='Ticket',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('ticket_id',models.CharField(max_length=30,unique=True)),('qr_code',models.ImageField(blank=True,null=True,upload_to='qr_codes/')),('issue_date',models.DateField(auto_now_add=True)),('attendee',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='ticket',to='core.attendee')),('event',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='core.event'))]),
        migrations.CreateModel(name='ResourceAllocation',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('quantity',models.PositiveIntegerField()),('status',models.CharField(default='Allocated',max_length=20)),('event',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='resource_allocations',to='core.event')),('resource',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='allocations',to='core.resource'))]),
        migrations.CreateModel(name='Vendor',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=150)),('service_type',models.CharField(max_length=100)),('phone',models.CharField(max_length=10)),('email',models.EmailField(max_length=254)),('availability',models.BooleanField(default=True)),('quality',models.PositiveSmallIntegerField(default=0)),('timeliness',models.PositiveSmallIntegerField(default=0)),('cost_rating',models.PositiveSmallIntegerField(default=0)),('communication',models.PositiveSmallIntegerField(default=0)),('overall_rating',models.DecimalField(decimal_places=1,default=0,max_digits=3))]),
        migrations.CreateModel(name='VendorAssignment',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('service',models.CharField(max_length=100)),('status',models.CharField(choices=[('Assigned','Assigned'),('Completed','Completed'),('Cancelled','Cancelled')],default='Assigned',max_length=20)),('event',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='vendor_assignments',to='core.event')),('vendor',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='assignments',to='core.vendor'))]),
        migrations.CreateModel(name='Notification',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('recipient_type',models.CharField(choices=[('Participant','Participant'),('Vendor','Vendor')],max_length=20)),('recipient',models.CharField(max_length=150)),('message',models.TextField()),('created_at',models.DateTimeField(auto_now_add=True)),('sent',models.BooleanField(default=False))]),
    ]
