# Generated by Django 5.2.17 on 2026-08-23 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_record', to='core.event')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Venue', 'Venue'), ('Catering', 'Catering'), ('Equipment', 'Equipment'), ('Transportation', 'Transportation'), ('Decoration', 'Decoration'), ('Marketing', 'Marketing'), ('Photography', 'Photography'), ('Security', 'Security'), ('Other', 'Other')], max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('expense_date', models.DateField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.event')),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('Registration', 'Registration'), ('Sponsorship', 'Sponsorship'), ('Vendor Fee', 'Vendor Fee'), ('Donation', 'Donation'), ('Other', 'Other')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_date', models.DateField(auto_now_add=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='core.event')),
            ],
        ),
    ]
