# Generated by Django 5.2.17 on 2026-08-30 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_budget_expense_revenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('EVENT', 'Event'), ('PAYMENT', 'Payment'), ('EXPENSE', 'Expense'), ('SPONSORSHIP', 'Sponsorship'), ('VENDOR', 'Vendor'), ('RESOURCE', 'Resource'), ('CUSTOM', 'Custom')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('reminder_date', models.DateTimeField()),
                ('recipient', models.CharField(max_length=150)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.event')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('sponsorship_type', models.CharField(choices=[('Title Sponsor', 'Title Sponsor'), ('Gold Sponsor', 'Gold Sponsor'), ('Silver Sponsor', 'Silver Sponsor'), ('Bronze Sponsor', 'Bronze Sponsor'), ('Food Sponsor', 'Food Sponsor'), ('Technology Sponsor', 'Technology Sponsor'), ('Media Sponsor', 'Media Sponsor'), ('Other', 'Other')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RECEIVED', 'Payment Received')], default='PROPOSED', max_length=30)),
                ('benefits', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='core.event')),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(choices=[('EVENT', 'Event'), ('EXPENSE', 'Expense'), ('SPONSORSHIP', 'Sponsorship'), ('VENUE', 'Venue'), ('RESOURCE', 'Resource'), ('VENDOR', 'Vendor')], max_length=30)),
                ('requested_by', models.CharField(max_length=150)),
                ('approved_by', models.CharField(blank=True, max_length=150)),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='core.event')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='core.expense')),
                ('sponsorship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='core.sponsorship')),
            ],
        ),
    ]
